ALTER TABLE SPXS RENAME COLUMN "('Adj Close', 'SPXS')" TO Adj_Close;
ALTER TABLE SPXS RENAME COLUMN "('Close', 'SPXS')" TO Close;
ALTER TABLE SPXS RENAME COLUMN "('High', 'SPXS')" TO High;
ALTER TABLE SPXS RENAME COLUMN "('Low', 'SPXS')" TO Low;
ALTER TABLE SPXS RENAME COLUMN "('Open', 'SPXS')" TO Open;
ALTER TABLE SPXS RENAME COLUMN "('Volume', 'SPXS')" TO Volume; 