ALTER TABLE SPXL RENAME COLUMN "('Adj Close', 'SPXL')" TO Adj_Close;
ALTER TABLE SPXL RENAME COLUMN "('Close', 'SPXL')" TO Close;
ALTER TABLE SPXL RENAME COLUMN "('High', 'SPXL')" TO High;
ALTER TABLE SPXL RENAME COLUMN "('Low', 'SPXL')" TO Low;
ALTER TABLE SPXL RENAME COLUMN "('Open', 'SPXL')" TO Open;
ALTER TABLE SPXL RENAME COLUMN "('Volume', 'SPXL')" TO Volume; 