ALTER TABLE BAR RENAME COLUMN "('Adj Close', 'BAR')" TO Adj_Close;
ALTER TABLE BAR RENAME COLUMN "('Close', 'BAR')" TO Close;
ALTER TABLE BAR RENAME COLUMN "('High', 'BAR')" TO High;
ALTER TABLE BAR RENAME COLUMN "('Low', 'BAR')" TO Low;
ALTER TABLE BAR RENAME COLUMN "('Open', 'BAR')" TO Open;
ALTER TABLE BAR RENAME COLUMN "('Volume', 'BAR')" TO Volume; 