ALTER TABLE BND RENAME COLUMN "('Adj Close', 'BND')" TO Adj_Close;
ALTER TABLE BND RENAME COLUMN "('Close', 'BND')" TO Close;
ALTER TABLE BND RENAME COLUMN "('High', 'BND')" TO High;
ALTER TABLE BND RENAME COLUMN "('Low', 'BND')" TO Low;
ALTER TABLE BND RENAME COLUMN "('Open', 'BND')" TO Open;
ALTER TABLE BND RENAME COLUMN "('Volume', 'BND')" TO Volume; 