ALTER TABLE SPY RENAME COLUMN "('Adj Close', 'SPY')" TO Adj_Close;
ALTER TABLE SPY RENAME COLUMN "('Close', 'SPY')" TO Close;
ALTER TABLE SPY RENAME COLUMN "('High', 'SPY')" TO High;
ALTER TABLE SPY RENAME COLUMN "('Low', 'SPY')" TO Low;
ALTER TABLE SPY RENAME COLUMN "('Open', 'SPY')" TO Open;
ALTER TABLE SPY RENAME COLUMN "('Volume', 'SPY')" TO Volume; 